package mockery

import (
	"errors"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"testing"
)

// MockSMS is an autogenerated mock type for the SMS type
type MockSMS struct {
	mock.Mock
}

// Send provides a mock function with given fields: number, text
func (_m *MockSMS) Send(number int, text string) error {
	ret := _m.Called(number, text)
	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(number, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

var _ SMS = (*MockSMS)(nil)

func TestSendHelloWorld(t *testing.T) {
	sampleErr := errors.New("some error")
	tests := map[string]struct {
		number int
		smsErr error
		err    error
	}{
		"successful":       {0132423444, nil, nil},
		"propagates error": {0132423444, sampleErr, sampleErr},
	}
	for _, test := range tests {
		sms := &MockSMS{}
		sms.On("Send", test.number, "Hello, world!").Return(test.smsErr).Once()
		m := &Messager{
			sms: sms,
		}

		err := m.SendHelloWorld(test.number)
		assert.Equal(t, test.err, err)
		sms.AssertExpectations(t)
	}
}
